#单机测试需要不同端口，分布式发布可以相同端口
#server:
#  port: 8090

spring:
  application:
    name: service-provider

springcloud:
  bus:
    update-properties:
      msg: "changed by 2020-03-18 10:47"

address:
  city-name: 梅州
