spring:
  application:
    name: service-config-center-node
        
message: from dev git message! node 02

server:
  port: 8763
eureka:
  dashboard:
    enabled: false   # 开启显示面板(默认开启)
    path: /         # 设置面板访问路径，默认为'/'
  datacenter: cloud # 云数据中心
  environment: test # 当前环境为测试环境
  instance:
    hostname: scc2
    instance-id: ${spring.application.name}:${server.port} #优先于metadataMap下的设置
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    appname: service-config-center-node
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://scc:8761/eureka/,http://scc1:8762/eureka/
