spring:
  profiles:
    active: 
  application:
    name: EurekaConsumer
server:
  port: 8083
eureka:
  instance:
    hostname: localhost
  appname: eureka-consumer
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
