server.port: 8761
spring:
    application:
        name: eureka-service-config-center

message: from dev branch message!

eureka:
  instance:
    hostname: localhost
  appname: eureka-serv-config-center
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
