spring:
  profiles:
    active: 
  application:
    name: only-ribbon-consumer
server:
  port: 8092
eureka:
  instance:
    hostname: localhost
  appname: only-ribbon-consumer
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
