spring:
  profiles:
    active: 
  application:
    name: RibbonConsumer
server:
  port: 8091
eureka:
  instance:
    hostname: localhost
    appname: ribbon-consumer
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
