spring:
  profiles:
    active: 
  application:
    name: ServiceProvider
server:
  port: 8082
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    appname: serv-provider
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    eureka-server-connect-timeout-seconds: 10
